name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install CMake and boost
      run: |
        sudo apt-get install -y cmake
        sudo apt-get install -y libboost-all-dev

    - name: Configure, build, and test
      run: |
        mkdir build
        cd build
        cmake ..
        git describe --tags --abbrev=0
        cat ../src/version.h
        make check
