name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install CMake and boost
      run: |
        sudo apt-get install -y cmake
        sudo apt-get install -y libboost-all-dev

    - name: Configure, build, and test
      run: |
        mkdir build
        cd build
        cmake ..
        make -j2 check

  build-ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install CMake and boost
      run: |
        sudo apt-get install -y cmake
        sudo apt-get install -y libboost-all-dev

    - name: Configure, build, and test
      run: |
        mkdir build
        cd build
        cmake -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ ..
        make -j2 check

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install CMake and Boost
      run: |
        brew install cmake
        brew install boost

    - name: Configure, build, and test
      run: |
        mkdir build
        cd build
        cmake ..
        make -j2 check
