name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up CMake
      run: sudo apt-get install -y cmake
      
    - name: Install Boost
      run: sudo apt-get install -y libboost-all-dev

    - name: Configure, build, and test
      run: |
        mkdir build
        cd build
        cmake ..
        cat ../src/include.h
        make check
